// src/lib/realtimeDb.js
// All Firebase Realtime Database helper functions.
//
// HOST PROTECTION MODEL
// ─────────────────────
// Firebase rules enforce structure (field types, immutable hostToken, one-way
// submittedCode lock). Host-only operations (stage changes, result saving, etc.)
// are protected at the application layer: every host function calls assertHost()
// which reads the stored hostToken from Firebase and compares it to the token
// the host holds in sessionStorage. An attacker without the token cannot trigger
// host operations through this module.

import { db } from '../firebase';
import {
  ref,
  set,
  get,
  update,
  onValue,
  off,
  runTransaction,
  serverTimestamp,
} from 'firebase/database';
import { MAX_PLAYERS, QUESTION_DURATION_MS, CODE_ENTRY_DURATION_MS } from './constants';
import { serverNow } from './serverClock';

// ─── VALIDATION ──────────────────────────────────────────────────────────────

function isValidCode(code) {
  if (typeof code !== 'string' || code.length !== 4) return false;
  return /^\d{4}$/.test(code);
}

// ─── HOST AUTH (application layer) ───────────────────────────────────────────

/**
 * Verify that hostToken matches the one stored in Firebase for this room.
 * Returns true/false.
 */
export async function verifyHostToken(roomCode, hostToken) {
  if (!hostToken) return false;
  const snap = await get(ref(db, `rooms/${roomCode}/hostToken`));
  return snap.exists() && snap.val() === hostToken;
}

/**
 * Throws if the hostToken is invalid. Call before every host write.
 */
async function assertHost(roomCode, hostToken) {
  const valid = await verifyHostToken(roomCode, hostToken);
  if (!valid) throw new Error('Unauthorized: invalid host token.');
}

// ─── ROOM ────────────────────────────────────────────────────────────────────

/**
 * Create a new room. Returns null on success, error string on failure.
 * hostToken is generated by the host client and stored permanently in the room.
 * Firebase rules ensure it cannot be changed after creation.
 */
export async function createRoom(roomCode, setId, hostToken) {
  if (!hostToken) return 'Missing host token.';
  const roomRef = ref(db, `rooms/${roomCode}`);
  const snap = await get(roomRef);
  if (snap.exists()) return 'A room with that code already exists.';

  await set(roomRef, {
    roomCode,
    stage: 'waiting',
    setId,
    questionIndex: 0,
    questionEndsAt: null,
    codeEntryEndsAt: null,
    hostToken,
    roundId: 1,
    createdAt: serverTimestamp(),
    players: {},
    result: null,
  });
  return null;
}

/**
 * Reset a room back to waiting state. Keeps roomCode, setId, and hostToken.
 * Uses update() on individual fields + set(null) on players — never set()
 * on the room root — because Firebase rules prevent overwriting an existing room.
 */
export async function resetRoom(roomCode, hostToken, newSetId) {
  await assertHost(roomCode, hostToken);

  // Read current roundId to increment it
  const roundSnap = await get(ref(db, `rooms/${roomCode}/roundId`));
  const currentRound = roundSnap.exists() ? roundSnap.val() : 0;

  const updates = {
    stage: 'waiting',
    questionIndex: 0,
    questionEndsAt: null,
    codeEntryEndsAt: null,
    result: null,
    roundId: currentRound + 1,
  };

  // Rotate to a new quiz set if provided
  if (newSetId) updates.setId = newSetId;

  await update(ref(db, `rooms/${roomCode}`), updates);

  // Clear all players (players/.write = data.parent().exists() → allowed)
  await set(ref(db, `rooms/${roomCode}/players`), null);
}

// ─── PLAYERS ─────────────────────────────────────────────────────────────────

/**
 * Join a room using a Firebase transaction to atomically enforce:
 *   - room exists and is in "waiting" stage
 *   - max 5 players
 *   - no duplicate names
 * Returns null on success, error string on failure.
 */
export async function joinRoom(roomCode, playerId, playerName) {
  const roomRef = ref(db, `rooms/${roomCode}`);

  // Pre-check: verify room exists before running transaction.
  // (runTransaction may pass null on its first invocation even when data exists,
  //  so we cannot rely on the callback's first value to detect missing rooms.)
  const existsSnap = await get(roomRef);
  if (!existsSnap.exists()) return 'Room not found.';

  let errorMsg = null;

  const { committed } = await runTransaction(roomRef, (room) => {
    // On first invocation the local cache may be empty — let Firebase retry.
    if (!room) return room;

    if (room.stage !== 'waiting') { errorMsg = 'The game has already started.'; return; }

    const players = room.players || {};
    const playerList = Object.values(players);

    if (playerList.length >= MAX_PLAYERS) {
      errorMsg = `Room is full (max ${MAX_PLAYERS} players).`;
      return;
    }

    const trimmedName = playerName.trim();
    if (playerList.some((p) => p.name.toLowerCase() === trimmedName.toLowerCase())) {
      errorMsg = 'That name is already taken in this room.';
      return;
    }

    if (!room.players) room.players = {};
    room.players[playerId] = {
      name: trimmedName,
      joinedAt: Date.now(),
      submittedCode: null,
      submittedAt: null,
    };
    return room;
  });

  if (!committed && !errorMsg) errorMsg = 'Could not join. Please try again.';
  return errorMsg;
}

/**
 * Check whether a player is still present in a room (for reconnect).
 */
export async function checkPlayerExists(roomCode, playerId) {
  const snap = await get(ref(db, `rooms/${roomCode}/players/${playerId}`));
  return snap.exists();
}

/**
 * Get the current roundId for a room.
 */
export async function getRoundId(roomCode) {
  const snap = await get(ref(db, `rooms/${roomCode}/roundId`));
  return snap.exists() ? snap.val() : null;
}

// ─── GAMEPLAY ─────────────────────────────────────────────────────────────────

/**
 * Submit a player's 4-digit code.
 * - Validates format (exactly 4 digits, each 1–4)
 * - Checks room is in code_entry stage
 * - Transaction prevents double-submit at the app layer
 *   (Firebase rules also enforce submittedCode immutability at the DB layer)
 * Returns null on success, error string on failure.
 */
export async function submitCode(roomCode, playerId, code) {
  if (!isValidCode(code)) return 'Invalid code. Use exactly 4 digits, each between 1 and 4.';

  const stageSnap = await get(ref(db, `rooms/${roomCode}/stage`));
  if (!stageSnap.exists()) return 'Room not found.';
  if (stageSnap.val() !== 'code_entry') return 'Code entry is not open right now.';

  const playerRef = ref(db, `rooms/${roomCode}/players/${playerId}`);
  let errorMsg = null;

  await runTransaction(playerRef, (player) => {
    if (!player) return player; // local cache empty — let Firebase retry
    if (player.submittedCode !== null) { errorMsg = 'You have already submitted your code.'; return; }
    player.submittedCode = code;
    player.submittedAt = Date.now();
    return player;
  });

  return errorMsg;
}

/**
 * Advance room to a specific stage. Host-only.
 */
export async function updateStage(roomCode, stage, hostToken) {
  await assertHost(roomCode, hostToken);
  await update(ref(db, `rooms/${roomCode}`), { stage });
}

/**
 * Begin a question: sets stage, questionIndex, and a server-synced deadline.
 * Uses serverNow() so all clients count down against the same clock.
 */
export async function startQuestion(roomCode, questionIndex, hostToken) {
  await assertHost(roomCode, hostToken);
  await update(ref(db, `rooms/${roomCode}`), {
    stage: 'question',
    questionIndex,
    questionEndsAt: serverNow() + QUESTION_DURATION_MS,
  });
}

/**
 * Open the code-entry phase with a server-synced deadline.
 */
export async function openCodeEntry(roomCode, hostToken) {
  await assertHost(roomCode, hostToken);
  await update(ref(db, `rooms/${roomCode}`), {
    stage: 'code_entry',
    codeEntryEndsAt: serverNow() + CODE_ENTRY_DURATION_MS,
  });
}

/**
 * Save the calculated result and move room to "result" stage.
 * Combines both writes so the UI transition is atomic.
 */
export async function saveResult(roomCode, result, hostToken) {
  await assertHost(roomCode, hostToken);
  await set(ref(db, `rooms/${roomCode}/result`), result);
  await update(ref(db, `rooms/${roomCode}`), { stage: 'result' });
}

// ─── LISTENER ─────────────────────────────────────────────────────────────────

/**
 * Subscribe to live room updates. Returns an unsubscribe function for
 * useEffect cleanup.
 */
export function listenToRoom(roomCode, callback) {
  const roomRef = ref(db, `rooms/${roomCode}`);
  onValue(roomRef, (snap) => callback(snap.exists() ? snap.val() : null));
  return () => off(roomRef);
}
